# lextab.py. This file automatically created by PLY (version 3.11). Don't edit!
_tabversion   = '3.10'
_lextokens    = set(('ABRE_COL', 'ABRE_PAR', 'ADICAO', 'ATE', 'ATRIBUICAO', 'DIFERENCA', 'DIVISAO', 'DOIS_PONTOS', 'ENTAO', 'ESCREVA', 'E_LOGICO', 'FECHA_COL', 'FECHA_PAR', 'FIM', 'FLUTUANTE', 'ID', 'IGUALDADE', 'INTEIRO', 'LEIA', 'MAIOR', 'MAIOR_IGUAL', 'MENOR', 'MENOR_IGUAL', 'MULTIPLICACAO', 'NEGACAO', 'NUM_INTEIRO', 'NUM_NOTACAO_CIENTIFICA', 'NUM_PONTO_FLUTUANTE', 'OU_LOGICO', 'REPITA', 'RETORNA', 'SE', 'SENAO', 'SUBTRACAO', 'VIRGULA'))
_lexreflags   = 64
_lexliterals  = ''
_lexstateinfo = {'INITIAL': 'inclusive'}
_lexstatere   = {'INITIAL': [('(?P<t_ID>(([a-zA-ZáÁãÃàÀéÉíÍóÓõÕ])(([0-9])+|_|([a-zA-ZáÁãÃàÀéÉíÍóÓõÕ]))*))|(?P<t_COMENTARIO>(\\{((.|\\n)*?)\\}))|(?P<t_newline>\\n+)|(?P<t_NUM_NOTACAO_CIENTIFICA>(([\\-\\+]?)([1-9])\\.([0-9])+[eE]([\\-\\+]?)([0-9])+))|(?P<t_NUM_PONTO_FLUTUANTE>\\d+[eE][-+]?\\d+|(\\.\\d+|\\d+\\.\\d*)([eE][-+]?\\d+)?)|(?P<t_NUM_INTEIRO>(([\\-\\+]?)([0-9])+))|(?P<t_OU_LOGICO>\\|\\|)|(?P<t_ADICAO>\\+)|(?P<t_MULTIPLICACAO>\\*)|(?P<t_ABRE_PAR>\\()|(?P<t_FECHA_PAR>\\))|(?P<t_ABRE_COL>\\[)|(?P<t_FECHA_COL>\\])|(?P<t_ATRIBUICAO>:=)|(?P<t_E_LOGICO>&&)|(?P<t_DIFERENCA><>)|(?P<t_MENOR_IGUAL><=)|(?P<t_MAIOR_IGUAL>>=)|(?P<t_SUBTRACAO>-)|(?P<t_DIVISAO>/)|(?P<t_VIRGULA>,)|(?P<t_DOIS_PONTOS>:)|(?P<t_NEGACAO>!)|(?P<t_MENOR><)|(?P<t_MAIOR>>)|(?P<t_IGUALDADE>=)', [None, ('t_ID', 'ID'), None, None, None, None, None, ('t_COMENTARIO', 'COMENTARIO'), None, None, None, ('t_newline', 'newline'), ('t_NUM_NOTACAO_CIENTIFICA', 'NUM_NOTACAO_CIENTIFICA'), None, None, None, None, None, None, ('t_NUM_PONTO_FLUTUANTE', 'NUM_PONTO_FLUTUANTE'), None, None, ('t_NUM_INTEIRO', 'NUM_INTEIRO'), None, None, None, (None, 'OU_LOGICO'), (None, 'ADICAO'), (None, 'MULTIPLICACAO'), (None, 'ABRE_PAR'), (None, 'FECHA_PAR'), (None, 'ABRE_COL'), (None, 'FECHA_COL'), (None, 'ATRIBUICAO'), (None, 'E_LOGICO'), (None, 'DIFERENCA'), (None, 'MENOR_IGUAL'), (None, 'MAIOR_IGUAL'), (None, 'SUBTRACAO'), (None, 'DIVISAO'), (None, 'VIRGULA'), (None, 'DOIS_PONTOS'), (None, 'NEGACAO'), (None, 'MENOR'), (None, 'MAIOR'), (None, 'IGUALDADE')])]}
_lexstateignore = {'INITIAL': ' \t'}
_lexstateerrorf = {'INITIAL': 't_error'}
_lexstateeoff = {}
